/*
 jquery.layout 1.3.0 - Release Candidate 29.9
 $Date: 2010-10-20 08:00:00 (Wed, 20 Oct 2010) $
 $Rev: 30299 $

 Copyright (c) 2010 
 Fabrizio Balliano (http://www.fabrizioballiano.net)
 Kevin Dalman (http://allpro.net)

 Dual licensed under the GPL (http://www.gnu.org/licenses/gpl.html)
 and MIT (http://www.opensource.org/licenses/mit-license.php) licenses.

 Docs: http://layout.jquery-dev.net/documentation.html
 Tips: http://layout.jquery-dev.net/tips.html
 Help: http://groups.google.com/group/jquery-ui-layout
*/
(function(f){var F=f.browser;f.layout={browser:{mozilla:!!F.mozilla,webkit:!!F.webkit||!!F.safari,msie:!!F.msie,isIE6:!!F.msie&&F.version==6,boxModel:!1},scrollbarWidth:function(){return window.scrollbarWidth||f.layout.getScrollbarSize("width")},scrollbarHeight:function(){return window.scrollbarHeight||f.layout.getScrollbarSize("height")},getScrollbarSize:function(h){var q=f('<div style="position: absolute; top: -10000px; left: -10000px; width: 100px; height: 100px; overflow: scroll;"></div>').appendTo("body"),
p={width:q.width()-q[0].clientWidth,height:q.height()-q[0].clientHeight};q.remove();window.scrollbarWidth=p.width;window.scrollbarHeight=p.height;return h.match(/^(width|height)$/i)?p[h]:p},showInvisibly:function(h,q){if(!h)return{};h.jquery||(h=f(h));var p={display:h.css("display"),visibility:h.css("visibility")};return q||p.display=="none"?(h.css({display:"block",visibility:"hidden"}),p):{}},getElemDims:function(h){var q={},p=q.css={},t={},G,H,I=h.offset();q.offsetLeft=I.left;q.offsetTop=I.top;
f.each("Left,Right,Top,Bottom".split(","),function(x,B){G=p["border"+B]=f.layout.borderWidth(h,B);H=p["padding"+B]=f.layout.cssNum(h,"padding"+B);t[B]=G+H;q["inset"+B]=H});q.offsetWidth=h.innerWidth();q.offsetHeight=h.innerHeight();q.outerWidth=h.outerWidth();q.outerHeight=h.outerHeight();q.innerWidth=q.outerWidth-t.Left-t.Right;q.innerHeight=q.outerHeight-t.Top-t.Bottom;p.width=h.width();p.height=h.height();return q},getElemCSS:function(f,q){var p={},t=f[0].style,G=q.split(","),H="Top,Bottom,Left,Right".split(","),
I="Color,Style,Width".split(","),x,B,F,N,O,Y;for(N=0;N<G.length;N++)if(x=G[N],x.match(/(border|padding|margin)$/))for(O=0;O<4;O++)if(B=H[O],x=="border")for(Y=0;Y<3;Y++)F=I[Y],p[x+B+F]=t[x+B+F];else p[x+B]=t[x+B];else p[x]=t[x];return p},cssWidth:function(h,q){var p=f.layout.borderWidth,t=f.layout.cssNum;if(q<=0)return 0;if(!f.layout.browser.boxModel)return q;p=q-p(h,"Left")-p(h,"Right")-t(h,"paddingLeft")-t(h,"paddingRight");return p>0?p:0},cssHeight:function(h,q){var p=f.layout.borderWidth,t=f.layout.cssNum;
if(q<=0)return 0;if(!f.layout.browser.boxModel)return q;p=q-p(h,"Top")-p(h,"Bottom")-t(h,"paddingTop")-t(h,"paddingBottom");return p>0?p:0},cssNum:function(h,q){h.jquery||(h=f(h));var p=f.layout.showInvisibly(h),t=parseInt(f.curCSS(h[0],q,!0),10)||0;h.css(p);return t},borderWidth:function(h,q){h.jquery&&(h=h[0]);var p="border"+q.substr(0,1).toUpperCase()+q.substr(1);return f.curCSS(h,p+"Style",!0)=="none"?0:parseInt(f.curCSS(h,p+"Width",!0),10)||0},isMouseOverElem:function(h,q){var p=f(q||this),t=
p.offset(),G=t.top,t=t.left,H=t+p.outerWidth(),p=G+p.outerHeight(),I=h.pageX,x=h.pageY;return f.layout.browser.msie&&I<0&&x<0||I>=t&&I<=H&&x>=G&&x<=p}};f.fn.layout=function(h){var q,p,t,G,H,I,x;function B(a){if(!a)return!0;var b=a.keyCode;if(b<33)return!0;var c={38:"north",40:"south",37:"west",39:"east"},e=a.shiftKey,d=a.ctrlKey,j,g,i,m;d&&b>=37&&b<=40&&n[c[b]].enableCursorHotkey?m=c[b]:(d||e)&&f.each(k.borderPanes.split(","),function(a,c){j=n[c];g=j.customHotkey;i=j.customHotkeyModifier;if(e&&i==
"SHIFT"||d&&i=="CTRL"||d&&e)if(g&&b==(isNaN(g)||g<=9?g.toUpperCase().charCodeAt(0):g))return m=c,!1});if(!m||!r[m]||!n[m].closable||l[m].isHidden)return!0;aa(m);a.stopPropagation();return a.returnValue=!1}function F(a){this&&this.tagName&&(a=this);var b;J(a)?b=r[a]:f(a).data("layoutRole")?b=f(a):f(a).parents().each(function(){if(f(this).data("layoutRole"))return b=f(this),!1});if(b&&b.length){var c=b.data("layoutEdge"),a=l[c];a.cssSaved&&N(c);if(a.isSliding||a.isResizing||a.isClosed)a.cssSaved=!1;
else{var e={zIndex:k.zIndex.pane_normal+2},d={},j=b.css("overflow"),g=b.css("overflowX"),i=b.css("overflowY");if(j!="visible")d.overflow=j,e.overflow="visible";if(g&&!g.match(/visible|auto/))d.overflowX=g,e.overflowX="visible";if(i&&!i.match(/visible|auto/))d.overflowY=g,e.overflowY="visible";a.cssSaved=d;b.css(e);f.each(k.allPanes.split(","),function(a,b){b!=c&&N(b)})}}}function N(a){this&&this.tagName&&(a=this);var b;J(a)?b=r[a]:f(a).data("layoutRole")?b=f(a):f(a).parents().each(function(){if(f(this).data("layoutRole"))return b=
f(this),!1});if(b&&b.length){var a=b.data("layoutEdge"),a=l[a],c=a.cssSaved||{};!a.isSliding&&!a.isResizing&&b.css("zIndex",k.zIndex.pane_normal);b.css(c);a.cssSaved=!1}}function O(a,b,c){var e=f(a);if(e.length)if(k.borderPanes.indexOf(b)==-1)alert(q+t.toLowerCase()+": "+b);else return a=n[b].buttonClass+"-"+c,e.addClass(a+" "+a+"-"+b).data("layoutName",n.name),e;else alert(q+p+": "+a);return null}function Y(a,b,c){switch(b.toLowerCase()){case "toggle":na(a,c);break;case "open":oa(a,c);break;case "close":Ba(a,
c);break;case "pin":Ca(a,c);break;case "toggle-slide":na(a,c,!0);break;case "open-slide":oa(a,c,!0)}}function na(a,b,c){(a=O(a,b,"toggle"))&&a.click(function(a){aa(b,!!c);a.stopPropagation()})}function oa(a,b,c){(a=O(a,b,"open"))&&a.attr("title",G).click(function(a){T(b,!!c);a.stopPropagation()})}function Ba(a,b){var c=O(a,b,"close");c&&c.attr("title",H).click(function(a){M(b);a.stopPropagation()})}function Ca(a,b){var c=O(a,b,"pin");if(c){var e=l[b];c.click(function(a){pa(f(this),b,e.isSliding||
e.isClosed);e.isSliding||e.isClosed?T(b):M(b);a.stopPropagation()});pa(c,b,!e.isClosed&&!e.isSliding);k[b].pins.push(a)}}function qa(a,b){f.each(k[a].pins,function(c,e){pa(f(e),a,b)})}function pa(a,b,c){var e=a.attr("pin");if(!(e&&c==(e=="down"))){var e=n[b].buttonClass+"-pin",d=e+"-"+b,b=e+"-up "+d+"-up",e=e+"-down "+d+"-down";a.attr("pin",c?"down":"up").attr("title",c?I:x).removeClass(c?b:e).addClass(c?e:b)}}function Da(a){for(var a=f.extend({},n.cookie,a||{}).name||n.name||"Layout",b=document.cookie,
b=b?b.split(";"):[],c,e=0,d=b.length;e<d;e++)if(c=f.trim(b[e]).split("="),c[0]==a)return Ea(decodeURIComponent(c[1]));return""}function ra(a,b){var c=f.extend({},n.cookie,b||{}),e=c.name||n.name||"Layout",d="",j="",g=!1;c.expires.toUTCString?j=c.expires:typeof c.expires=="number"&&(j=new Date,c.expires>0?j.setDate(j.getDate()+c.expires):(j.setYear(1970),g=!0));j&&(d+=";expires="+j.toUTCString());c.path&&(d+=";path="+c.path);c.domain&&(d+=";domain="+c.domain);c.secure&&(d+=";secure");g?(l.cookie={},
document.cookie=e+"="+d):(l.cookie=sa(a||c.keys),document.cookie=e+"="+encodeURIComponent(Fa(l.cookie))+d);return f.extend({},l.cookie)}function Ga(a){if(a=Da(a))l.cookie=f.extend({},a),Ha(a);return a}function Ha(a){f.extend(!0,n,a)}function sa(a){var b={},c={isClosed:"initClosed",isHidden:"initHidden"},e,d,j;if(!a)a=n.cookie.keys;f.isArray(a)&&(a=a.join(","));for(var a=a.replace(/__/g,".").split(","),g=0,i=a.length;g<i;g++)e=a[g].split("."),d=e[0],e=e[1],k.allPanes.indexOf(d)<0||(j=l[d][e],j!=void 0&&
(e=="isClosed"&&l[d].isSliding&&(j=!0),(b[d]||(b[d]={}))[c[e]?c[e]:e]=j));return b}function Fa(a){function b(a){var e=[],d=0,j,g,i;for(j in a)g=a[j],i=typeof g,i=="string"?g='"'+g+'"':i=="object"&&(g=b(g)),e[d++]='"'+j+'":'+g;return"{"+e.join(",")+"}"}return b(a)}function Ea(a){try{return window.eval("("+a+")")||{}}catch(b){return{}}}t="Pane";G="Open";H="Close";x="Pin";I="Un-Pin";p="selector";q="Error Adding Button \n\nInvalid ";var n={name:"",scrollToBookmarkOnLoad:!0,resizeWithWindow:!0,resizeWithWindowDelay:200,
resizeWithWindowMaxDelay:0,onresizeall_start:null,onresizeall_end:null,onload:null,onunload:null,autoBindCustomButtons:!1,zIndex:null,defaults:{applyDemoStyles:!1,closable:!0,resizable:!0,slidable:!0,initClosed:!1,initHidden:!1,contentSelector:".ui-layout-content",contentIgnoreSelector:".ui-layout-ignore",findNestedContent:!1,paneClass:"ui-layout-pane",resizerClass:"ui-layout-resizer",togglerClass:"ui-layout-toggler",buttonClass:"ui-layout-button",minSize:0,maxSize:0,spacing_open:6,spacing_closed:6,
togglerLength_open:50,togglerLength_closed:50,togglerAlign_open:"center",togglerAlign_closed:"center",togglerTip_open:H,togglerTip_closed:G,togglerContent_open:"",togglerContent_closed:"",resizerDblClickToggle:!0,autoResize:!0,autoReopen:!0,resizerDragOpacity:1,maskIframesOnResize:!0,resizeNestedLayout:!0,resizeWhileDragging:!1,resizeContentWhileDragging:!1,noRoomToOpenTip:"Not enough room to show this pane.",resizerTip:"Resize",sliderTip:"Slide Open",sliderCursor:"pointer",slideTrigger_open:"click",
slideTrigger_close:"mouseleave",hideTogglerOnSlide:!1,preventQuickSlideClose:!(!f.browser.webkit&&!f.browser.safari),preventPrematureSlideClose:!1,showOverflowOnHover:!1,enableCursorHotkey:!0,customHotkeyModifier:"SHIFT",fxName:"slide",fxSpeed:null,fxSettings:{},fxOpacityFix:!0,triggerEventsOnLoad:!1,triggerEventsWhileDragging:!0,onshow_start:null,onshow_end:null,onhide_start:null,onhide_end:null,onopen_start:null,onopen_end:null,onclose_start:null,onclose_end:null,onresize_start:null,onresize_end:null,
onsizecontent_start:null,onsizecontent_end:null,onswap_start:null,onswap_end:null,ondrag_start:null,ondrag_end:null},north:{paneSelector:".ui-layout-north",size:"auto",resizerCursor:"n-resize",customHotkey:""},south:{paneSelector:".ui-layout-south",size:"auto",resizerCursor:"s-resize",customHotkey:""},east:{paneSelector:".ui-layout-east",size:200,resizerCursor:"e-resize",customHotkey:""},west:{paneSelector:".ui-layout-west",size:200,resizerCursor:"w-resize",customHotkey:""},center:{paneSelector:".ui-layout-center",
minWidth:0,minHeight:0},useStateCookie:!1,cookie:{name:"",autoSave:!0,autoLoad:!0,domain:"",path:"",expires:"",secure:!1,keys:"north.size,south.size,east.size,west.size,north.isClosed,south.isClosed,east.isClosed,west.isClosed,north.isHidden,south.isHidden,east.isHidden,west.isHidden"}},ta={slide:{all:{duration:"fast"},north:{direction:"up"},south:{direction:"down"},east:{direction:"right"},west:{direction:"left"}},drop:{all:{duration:"slow"},north:{direction:"up"},south:{direction:"down"},east:{direction:"right"},
west:{direction:"left"}},scale:{all:{duration:"fast"}}},l={id:"layout"+(new Date).getTime(),initialized:!1,container:{},north:{},south:{},east:{},west:{},center:{},cookie:{}},k={allPanes:"north,south,west,east,center",borderPanes:"north,south,west,east",altSide:{north:"south",south:"north",east:"west",west:"east"},hidden:{visibility:"hidden"},visible:{visibility:"visible"},zIndex:{pane_normal:1,resizer_normal:2,iframe_mask:2,pane_sliding:100,pane_animate:1E3,resizer_drag:1E4},resizers:{cssReq:{position:"absolute",
padding:0,margin:0,fontSize:"1px",textAlign:"left",overflow:"hidden"},cssDemo:{background:"#DDD",border:"none"}},togglers:{cssReq:{position:"absolute",display:"block",padding:0,margin:0,overflow:"hidden",textAlign:"center",fontSize:"1px",cursor:"pointer",zIndex:1},cssDemo:{background:"#AAA"}},content:{cssReq:{position:"relative"},cssDemo:{overflow:"auto",padding:"10px"},cssDemoPane:{overflow:"hidden",padding:0}},panes:{cssReq:{position:"absolute",margin:0},cssDemo:{padding:"10px",background:"#FFF",
border:"1px solid #BBB",overflow:"auto"}},north:{side:"Top",sizeType:"Height",dir:"horz",cssReq:{top:0,bottom:"auto",left:0,right:0,width:"auto"},pins:[]},south:{side:"Bottom",sizeType:"Height",dir:"horz",cssReq:{top:"auto",bottom:0,left:0,right:0,width:"auto"},pins:[]},east:{side:"Right",sizeType:"Width",dir:"vert",cssReq:{left:"auto",right:0,top:"auto",bottom:"auto",height:"auto"},pins:[]},west:{side:"Left",sizeType:"Width",dir:"vert",cssReq:{left:0,right:"auto",top:"auto",bottom:"auto",height:"auto"},
pins:[]},center:{dir:"center",cssReq:{left:"auto",right:"auto",top:"auto",bottom:"auto",height:"auto",width:"auto"}}},E={data:{},set:function(a,b,c){E.clear(a);E.data[a]=setTimeout(b,c)},clear:function(a){var b=E.data;b[a]&&(clearTimeout(b[a]),delete b[a])}},J=function(a){try{return typeof a=="string"||typeof a=="object"&&a.constructor.toString().match(/string/i)!==null}catch(b){return!1}},z=function(a,b){return Math.max(a,b)},Va=function(a){var b,c={cookie:{},defaults:{fxSettings:{}},north:{fxSettings:{}},
south:{fxSettings:{}},east:{fxSettings:{}},west:{fxSettings:{}},center:{fxSettings:{}}},a=a||{};a.effects||a.cookie||a.defaults||a.north||a.south||a.west||a.east||a.center?c=f.extend(!0,c,a):f.each(a,function(a,d){b=a.split("__");if(!b[1]||c[b[0]])c[b[1]?b[0]:"defaults"][b[1]?b[1]:b[0]]=d});return c},Ia=function(a,b,c){function e(j){var g=k[j];g.doCallback?(d.push(j),j=g.callback.split(",")[1],j!=b&&!f.inArray(j,d)>=0&&e(j)):(g.doCallback=!0,g.callback=a+","+b+","+(c?1:0))}var d=[];f.each(k.borderPanes.split(","),
function(a,b){if(k[b].isMoving)return e(b),!1})},Ja=function(a){a=k[a];k.isLayoutBusy=!1;delete a.isMoving;if(a.doCallback&&a.callback){a.doCallback=!1;var b=a.callback.split(","),c=b[2]>0?!0:!1;b[0]=="open"?T(b[1],c):b[0]=="close"&&M(b[1],c);if(!a.doCallback)a.callback=null}},u=function(a,b){if(b){var c;try{if(typeof b=="function")c=b;else if(J(b))if(b.match(/,/)){var e=b.split(",");c=eval(e[0]);if(typeof c=="function"&&e.length>1)return c(e[1])}else c=eval(b);else return;if(typeof c=="function")return a&&
r[a]?c(a,r[a],f.extend({},l[a]),n[a],n.name):c(Ka,f.extend({},l),n,n.name)}catch(d){}}},La=function(a,b){if(!a)return{};a.jquery||(a=f(a));var c={display:a.css("display"),visibility:a.css("visibility")};return b||c.display=="none"?(a.css({display:"block",visibility:"hidden"}),c):{}},Ma=function(a){if(!l.browser.mozilla){var b=r[a];l[a].tagName=="IFRAME"?b.css(k.hidden).css(k.visible):b.find("IFRAME").css(k.hidden).css(k.visible)}},Z=function(a,b){a.jquery||(a=f(a));var c=La(a),e=parseInt(f.curCSS(a[0],
b,!0),10)||0;a.css(c);return e},da=function(a,b){a.jquery&&(a=a[0]);var c="border"+b.substr(0,1).toUpperCase()+b.substr(1);return f.curCSS(a,c+"Style",!0)=="none"?0:parseInt(f.curCSS(a,c+"Width",!0),10)||0},K=function(a,b){var c=J(a),e=c?r[a]:f(a);isNaN(b)&&(b=c?Q(a):e.outerWidth());if(b<=0)return 0;if(!l.browser.boxModel)return b;c=b-da(e,"Left")-da(e,"Right")-Z(e,"paddingLeft")-Z(e,"paddingRight");return c>0?c:0},L=function(a,b){var c=J(a),e=c?r[a]:f(a);isNaN(b)&&(b=c?Q(a):e.outerHeight());if(b<=
0)return 0;if(!l.browser.boxModel)return b;c=b-da(e,"Top")-da(e,"Bottom")-Z(e,"paddingTop")-Z(e,"paddingBottom");return c>0?c:0},ja=function(a){var b=k[a].dir,a={minWidth:1001-K(a,1E3),minHeight:1001-L(a,1E3)};if(b=="horz")a.minSize=a.minHeight;if(b=="vert")a.minSize=a.minWidth;return a},Wa=function(a,b,c){var e=a;J(a)?e=r[a]:a.jquery||(e=f(a));a=L(e,b);e.css({height:a,visibility:"visible"});a>0&&e.innerWidth()>0?c&&e.data("autoHidden")&&(e.show().data("autoHidden",!1),l.browser.mozilla||e.css(k.hidden).css(k.visible)):
c&&!e.data("autoHidden")&&e.hide().data("autoHidden",!0)},U=function(a,b,c){if(!c)c=k[a].dir;J(b)&&b.match(/%/)&&(b=parseInt(b,10)/100);if(b===0)return 0;else if(b>=1)return parseInt(b,10);else if(b>0){var a=n,e;c=="horz"?e=v.innerHeight-(r.north?a.north.spacing_open:0)-(r.south?a.south.spacing_open:0):c=="vert"&&(e=v.innerWidth-(r.west?a.west.spacing_open:0)-(r.east?a.east.spacing_open:0));return Math.floor(e*b)}else if(a=="center")return 0;else{e=r[a];var c=c=="horz"?"height":"width",a=La(e),d=
e.css(c);e.css(c,"auto");b=c=="height"?e.outerHeight():e.outerWidth();e.css(c,d).css(a);return b}},Q=function(a,b){var c=r[a],e=n[a],d=l[a],j=b?e.spacing_open:0,e=b?e.spacing_closed:0;return!c||d.isHidden?0:d.isClosed||d.isSliding&&b?e:k[a].dir=="horz"?c.outerHeight()+j:c.outerWidth()+j},R=function(a,b){var c=n[a],e=l[a],d=k[a],j=d.dir;d.side.toLowerCase();d.sizeType.toLowerCase();var d=b!=void 0?b:e.isSliding,g=c.spacing_open,i=k.altSide[a],f=l[i],P=r[i],A=!P||f.isVisible===!1||f.isSliding?0:j==
"horz"?P.outerHeight():P.outerWidth(),i=(!P||f.isHidden?0:n[i][f.isClosed!==!1?"spacing_closed":"spacing_open"])||0,f=j=="horz"?v.innerHeight:v.innerWidth,P=ja("center"),P=j=="horz"?z(n.center.minHeight,P.minHeight):z(n.center.minWidth,P.minWidth),d=f-g-(d?0:U("center",P,j)+A+i),j=e.minSize=z(U(a,c.minSize),ja(a).minSize),g=c.maxSize?U(a,c.maxSize):1E5,d=Math.min(g,d),d=e.maxSize=d,e=e.resizerPosition={},g=v.insetTop,A=v.insetLeft,i=v.innerWidth,f=v.innerHeight,c=c.spacing_open;switch(a){case "north":e.min=
g+j;e.max=g+d;break;case "west":e.min=A+j;e.max=A+d;break;case "south":e.min=g+f-d-c;e.max=g+f-j-c;break;case "east":e.min=A+i-d-c,e.max=A+i-j-c}},$=function(a){var b={},c=b.css={},e={},d,j,g=a.offset();b.offsetLeft=g.left;b.offsetTop=g.top;f.each("Left,Right,Top,Bottom".split(","),function(i,g){d=c["border"+g]=da(a,g);j=c["padding"+g]=Z(a,"padding"+g);e[g]=d+j;b["inset"+g]=j});b.offsetWidth=a.innerWidth();b.offsetHeight=a.innerHeight();b.outerWidth=a.outerWidth();b.outerHeight=a.outerHeight();b.innerWidth=
b.outerWidth-e.Left-e.Right;b.innerHeight=b.outerHeight-e.Top-e.Bottom;c.width=a.width();c.height=a.height();return b},ua=function(a,b){var c={},e=a[0].style,d=b.split(","),f="Top,Bottom,Left,Right".split(","),g="Color,Style,Width".split(","),i,m,k,l,n,h;for(l=0;l<d.length;l++)if(i=d[l],i.match(/(border|padding|margin)$/))for(n=0;n<4;n++)if(m=f[n],i=="border")for(h=0;h<3;h++)k=g[h],c[i+m+k]=e[i+m+k];else c[i+m]=e[i+m];else c[i]=e[i];return c},va=function(a,b){var c=f(a),e=c.data("layoutRole"),d=c.data("layoutEdge"),
j=n[d][e+"Class"],d="-"+d,g=c.hasClass(j+"-closed")?"-closed":"-open",i=g=="-closed"?"-open":"-closed",g=j+"-hover "+(j+d+"-hover ")+(j+g+"-hover ")+(j+d+g+"-hover ");b&&(g+=j+i+"-hover "+(j+d+i+"-hover "));e=="resizer"&&c.hasClass(j+"-sliding")&&(g+=j+"-sliding-hover "+(j+d+"-sliding-hover "));return f.trim(g)},ea=function(a,b){var c=b||this;f(c).addClass(va(c))},S=function(a,b){var c=b||this;f(c).removeClass(va(c,!0))},Xa=function(a){f("body").disableSelection();ea(a,this)},Na=function(a,b){var c=
b||this,e=f(c).data("layoutEdge"),d=e+"ResizerLeave";E.clear(d);b?l[e].isResizing||f("body").enableSelection():(S(a,this),E.set(d,function(){Na(a,c)},200))},Ya=function(){var a=Number(n.resizeWithWindowDelay)||100;a>0&&(E.clear("winResize"),E.set("winResize",function(){E.clear("winResize");E.clear("winResizeRepeater");ka()},a),E.data.winResizeRepeater||Oa())},Oa=function(){var a=Number(n.resizeWithWindowMaxDelay);a>0&&E.set("winResizeRepeater",function(){Oa();ka()},a)},Pa=function(){var a=n;l.cookie=
sa();a.useStateCookie&&a.cookie.autoSave&&ra();u(null,a.onunload)},Za=function(){f.each(k.borderPanes.split(","),function(a,b){var c=n[b];if(c.enableCursorHotkey||c.customHotkey)return f(document).bind("keydown."+w,B),!1})},$a=function(){function a(a){for(var c in b)a[c]!=void 0&&(a[b[c]]=a[c],delete a[c])}h=Va(h);var b={applyDefaultStyles:"applyDemoStyles"};a(h.defaults);f.each(k.allPanes.split(","),function(b,c){a(h[c])});h.effects&&(f.extend(ta,h.effects),delete h.effects);f.extend(n.cookie,h.cookie);
f.each("name,zIndex,scrollToBookmarkOnLoad,resizeWithWindow,resizeWithWindowDelay,resizeWithWindowMaxDelay,onresizeall,onresizeall_start,onresizeall_end,onload,onunload,autoBindCustomButtons,useStateCookie".split(","),function(a,b){h[b]!==void 0?n[b]=h[b]:h.defaults[b]!==void 0&&(n[b]=h.defaults[b],delete h.defaults[b])});f.each("paneSelector,resizerCursor,customHotkey".split(","),function(a,b){delete h.defaults[b]});f.extend(!0,n.defaults,h.defaults);k.center=f.extend(!0,{},k.panes,k.center);var c=
n.zIndex;if(c===0||c>0)k.zIndex.pane_normal=c,k.zIndex.resizer_normal=c+1,k.zIndex.iframe_mask=c+1;f.extend(n.center,h.center);var e=f.extend(!0,{},n.defaults,h.defaults,n.center),c="paneClass,contentSelector,applyDemoStyles,triggerEventsOnLoad,showOverflowOnHover,onresize,onresize_start,onresize_end,resizeNestedLayout,resizeContentWhileDragging,onsizecontent,onsizecontent_start,onsizecontent_end".split(",");f.each(c,function(a,b){n.center[b]=e[b]});var d,j=n.defaults;f.each(k.borderPanes.split(","),
function(a,b){k[b]=f.extend(!0,{},k.panes,k[b]);d=n[b]=f.extend(!0,{},n.defaults,n[b],h.defaults,h[b]);if(!d.paneClass)d.paneClass="ui-layout-pane";if(!d.resizerClass)d.resizerClass="ui-layout-resizer";if(!d.togglerClass)d.togglerClass="ui-layout-toggler";f.each(["_open","_close",""],function(a,c){var e="fxName"+c,g="fxSpeed"+c,k="fxSettings"+c;d[e]=h[b][e]||h[b].fxName||h.defaults[e]||h.defaults.fxName||d[e]||d.fxName||j[e]||j.fxName||"none";var l=d[e];if(l=="none"||!f.effects||!f.effects[l]||!ta[l]&&
!d[k]&&!d.fxSettings)l=d[e]="none";l=ta[l]||{};e=l.all||{};l=l[b]||{};d[k]=f.extend({},e,l,j.fxSettings||{},j[k]||{},d.fxSettings,d[k],h.defaults.fxSettings,h.defaults[k]||{},h[b].fxSettings,h[b][k]||{});d[g]=h[b][g]||h[b].fxSpeed||h.defaults[g]||h.defaults.fxSpeed||d[g]||d[k].duration||d.fxSpeed||d.fxSettings.duration||j.fxSpeed||j.fxSettings.duration||l.duration||e.duration||"normal"})})},Ra=function(a){a=n[a].paneSelector;if(a.substr(0,1)==="#")return C.find(a).eq(0);else{var b=C.children(a).eq(0);
return b.length?b:C.children("form:first").children(a).eq(0)}},ab=function(){f.each(k.allPanes.split(","),function(a,b){var c=n[b],e=l[b],d=k[b],f=d.dir,g=b=="center",i={},m,h,A;V[b]=!1;m=r[b]=Ra(b);if(!m.length)return r[b]=!1,!0;m.data("layoutCSS")||m.data("layoutCSS",ua(m,"position,top,left,bottom,right,width,height,overflow,zIndex,display,backgroundColor,padding,margin,border"));m.data("layoutName",n.name).data("layoutRole","pane").data("layoutEdge",b).css(d.cssReq).css("zIndex",k.zIndex.pane_normal).css(c.applyDemoStyles?
d.cssDemo:{}).addClass(c.paneClass+" "+c.paneClass+"-"+b).bind("mouseenter."+w,ea).bind("mouseleave."+w,S);Sa(b,!1);if(!g)h=e.size=U(b,c.size),d=U(b,c.minSize)||1,A=U(b,c.maxSize)||1E5,h>0&&(h=z(Math.min(h,A),d));e.tagName=m.attr("tagName");e.edge=b;e.noRoom=!1;e.isVisible=!0;if(!g)e.isClosed=!1,e.isSliding=!1,e.isResizing=!1,e.isHidden=!1;switch(b){case "north":i.top=v.insetTop;i.left=v.insetLeft;i.right=v.insetRight;break;case "south":i.bottom=v.insetBottom;i.left=v.insetLeft;i.right=v.insetRight;
break;case "west":i.left=v.insetLeft;break;case "east":i.right=v.insetRight}if(f=="horz")i.height=z(1,L(b,h));else if(f=="vert")i.width=z(1,K(b,h));m.css(i);f!="horz"&&W(b,!0);m.css({visibility:"visible",display:"block"});c.initClosed&&c.closable?M(b,!0,!0):(c.initHidden||c.initClosed)&&wa(b);c.showOverflowOnHover&&m.hover(F,N)});Ta();f.each(k.borderPanes.split(","),function(a,b){r[b]&&l[b].isVisible&&(R(b),X(b))});W("center");f.each(k.allPanes.split(","),function(a,b){var c=n[b];r[b]&&c.triggerEventsOnLoad&&
l[b].isVisible&&u(b,c.onresize_end||c.onresize)});C.innerHeight()<2&&alert("UI Layout Initialization Warning\n\nThe layout-container \"CONTAINER\" has no height.\n\nTherefore the layout is 0-height and hence 'invisible'!".replace(/CONTAINER/,v.ref))},Ta=function(a){if(!a||a=="all")a=k.borderPanes;f.each(a.split(","),function(a,c){var e=r[c];y[c]=!1;D[c]=!1;if(e){var e=n[c],d=l[c],j=e.resizerClass,g=e.togglerClass;k[c].side.toLowerCase();var i="-"+c,m=y[c]=f("<div></div>"),h=e.closable?D[c]=f("<div></div>"):
!1;!d.isVisible&&e.slidable&&m.attr("title",e.sliderTip).css("cursor",e.sliderCursor);m.attr("id",e.paneSelector.substr(0,1)=="#"?e.paneSelector.substr(1)+"-resizer":"").data("layoutRole","resizer").data("layoutEdge",c).css(k.resizers.cssReq).css("zIndex",k.zIndex.resizer_normal).css(e.applyDemoStyles?k.resizers.cssDemo:{}).addClass(j+" "+j+i).appendTo(C);h&&(h.attr("id",e.paneSelector.substr(0,1)=="#"?e.paneSelector.substr(1)+"-toggler":"").data("layoutRole","toggler").data("layoutEdge",c).css(k.togglers.cssReq).css(e.applyDemoStyles?
k.togglers.cssDemo:{}).addClass(g+" "+g+i).appendTo(m).click(function(a){aa(c);a.stopPropagation()}).hover(ea,S),e.togglerContent_open&&f("<span>"+e.togglerContent_open+"</span>").data("layoutRole","togglerContent").data("layoutEdge",c).addClass("content content-open").css("display","none").appendTo(h).hover(ea,S),e.togglerContent_closed&&f("<span>"+e.togglerContent_closed+"</span>").data("layoutRole","togglerContent").data("layoutEdge",c).addClass("content content-closed").css("display","none").appendTo(h).hover(ea,
S));bb(c);d.isVisible?xa(c):(ya(c),fa(c,!0))}});ga("all")},Sa=function(a,b){var c=n[a],e=c.contentSelector,d=r[a],f;e&&(f=V[a]=c.findNestedContent?d.find(e).eq(0):d.children(e).eq(0));f&&f.length?(f.css(k.content.cssReq),c.applyDemoStyles&&(f.css(k.content.cssDemo),d.css(k.content.cssDemoPane)),l[a].content={},b!==!1&&ba(a)):V[a]=!1},cb=function(){var a;f.each("toggle,open,close,pin,toggle-slide,open-slide".split(","),function(b,c){f.each(k.borderPanes.split(","),function(b,d){f(".ui-layout-button-"+
c+"-"+d).each(function(){a=f(this).data("layoutName")||f(this).attr("layoutName");(a==void 0||a==n.name)&&Y(this,c,d)})})})},bb=function(a){var b=typeof f.fn.draggable=="function",c;if(!a||a=="all")a=k.borderPanes;f.each(a.split(","),function(a,d){var j=n[d],g=l[d],i=k[d],m=i.dir=="horz"?"top":"left",h,A;if(!b||!r[d]||!j.resizable)return j.resizable=!1,!0;var p=y[d],q=j.resizerClass,Qa=q+"-drag",t=q+"-"+d+"-drag",z=q+"-dragging",x=q+"-"+d+"-dragging",w=q+"-dragging-limit",B=!1;g.isClosed||p.attr("title",
j.resizerTip).css("cursor",j.resizerCursor);p.hover(Xa,Na);p.draggable({containment:C[0],axis:i.dir=="horz"?"y":"x",delay:0,distance:1,helper:"clone",opacity:j.resizerDragOpacity,addClasses:!1,zIndex:k.zIndex.resizer_drag,start:function(){j=n[d];g=l[d];A=j.resizeWhileDragging;if(!1===u(d,j.ondrag_start))return!1;k.isLayoutBusy=!0;g.isResizing=!0;E.clear(d+"_closeSlider");R(d);h=g.resizerPosition;p.addClass(Qa+" "+t);B=!1;c=f(j.maskIframesOnResize===!0?"iframe":j.maskIframesOnResize).filter(":visible");
var a,b=0;c.each(function(){a="ui-layout-mask-"+ ++b;f(this).data("layoutMaskID",a);f('<div id="'+a+'" class="ui-layout-mask ui-layout-mask-'+d+'"/>').css({background:"#fff",opacity:"0.001",zIndex:k.zIndex.iframe_mask,position:"absolute",width:this.offsetWidth+"px",height:this.offsetHeight+"px"}).css(f(this).position()).appendTo(this.parentNode)});f("body").disableSelection()},drag:function(a,b){B||(b.helper.addClass(z+" "+x).children().css("visibility","hidden"),B=!0,g.isSliding&&r[d].css("zIndex",
k.zIndex.pane_sliding));var c=0;if(b.position[m]<h.min)b.position[m]=h.min,c=-1;else if(b.position[m]>h.max)b.position[m]=h.max,c=1;c?(b.helper.addClass(w),window.defaultStatus="Panel has reached its "+(c>0&&d.match(/north|west/)||c<0&&d.match(/south|east/)?"maximum":"minimum")+" size"):(b.helper.removeClass(w),window.defaultStatus="");A&&D(a,b,d)},stop:function(a,b){f("body").enableSelection();window.defaultStatus="";p.removeClass(Qa+" "+t+" "+w);g.isResizing=!1;k.isLayoutBusy=!1;D(a,b,d,!0)}});
var D=function(a,b,d,e){var a=b.position,b=k[d],g;switch(d){case "north":g=a.top;break;case "west":g=a.left;break;case "south":g=v.offsetHeight-a.top-j.spacing_open;break;case "east":g=v.offsetWidth-a.left-j.spacing_open}if(e){if(f("div.ui-layout-mask").each(function(){this.parentNode.removeChild(this)}),!1===u(d,j.ondrag_end||j.ondrag))return!1}else c.each(function(){f("#"+f(this).data("layoutMaskID")).css(f(this).position()).css({width:this.offsetWidth+"px",height:this.offsetHeight+"px"})});za(d,
g-v["inset"+b.side])}})},wa=function(a,b){var c=n[a],e=l[a],d=r[a],f=y[a];if(d&&!e.isHidden&&!(l.initialized&&!1===u(a,c.onhide_start)))if(e.isSliding=!1,f&&f.hide(),!l.initialized||e.isClosed){if(e.isClosed=!0,e.isHidden=!0,e.isVisible=!1,d.hide(),W(k[a].dir=="horz"?"all":"center"),l.initialized||c.triggerEventsOnLoad)u(a,c.onhide_end||c.onhide)}else e.isHiding=!0,M(a,!1,b)},la=function(a,b,c,e){var d=l[a];if(r[a]&&d.isHidden&&!1!==u(a,n[a].onshow_start))d.isSliding=!1,d.isShowing=!0,b===!1?M(a,
!0):T(a,!1,c,e)},aa=function(a,b){J(a)||(a.stopImmediatePropagation(),a=f(this).data("layoutEdge"));var c=l[J(a)?f.trim(a):a==void 0||a==null?"":a];c.isHidden?la(a):c.isClosed?T(a,!!b):M(a)},db=function(a){var b=l[a];r[a].hide();b.isClosed=!0;b.isVisible=!1},M=function(a,b,c,e){function d(){if(i.isClosed){fa(a,!0);var b=k.altSide[a];l[b].noRoom&&(R(b),X(b));if(!e&&(l.initialized||g.triggerEventsOnLoad))m||u(a,g.onclose_end||g.onclose),m&&u(a,g.onshow_end||g.onshow),h&&u(a,g.onhide_end||g.onhide)}Ja(a)}
if(l.initialized){var f=r[a],g=n[a],i=l[a],c=!c&&!i.isClosed&&g.fxName_close!="none",m=i.isShowing,h=i.isHiding;delete i.isShowing;delete i.isHiding;if(f&&g.closable&&(b||!i.isClosed||m))if(k.isLayoutBusy)Ia("close",a,b);else if(m||!1!==u(a,g.onclose_start)){k[a].isMoving=!0;k.isLayoutBusy=!0;i.isClosed=!0;i.isVisible=!1;if(h)i.isHidden=!0;else if(m)i.isHidden=!1;i.isSliding?ha(a,!1):W(k[a].dir=="horz"?"all":"center",!1);ya(a);c?(ma(a,!0),f.hide(g.fxName_close,g.fxSettings_close,g.fxSpeed_close,function(){ma(a,
!1);d()})):(f.hide(),d())}}else db(a)},ya=function(a){var b=y[a],c=D[a],e=n[a],d=k[a].side.toLowerCase(),j=e.resizerClass,g=e.togglerClass,i="-"+a;b.css(d,v["inset"+k[a].side]).removeClass(j+"-open "+j+i+"-open").removeClass(j+"-sliding "+j+i+"-sliding").addClass(j+"-closed "+j+i+"-closed").unbind("dblclick."+w);e.resizable&&typeof f.fn.draggable=="function"&&b.draggable("disable").removeClass("ui-state-disabled").css("cursor","default").attr("title","");c&&(c.removeClass(g+"-open "+g+i+"-open").addClass(g+
"-closed "+g+i+"-closed").attr("title",e.togglerTip_closed),c.children(".content-open").hide(),c.children(".content-closed").css("display","block"));qa(a,!1);l.initialized&&ga("all")},T=function(a,b,c,e){function d(){i.isVisible&&(Ma(a),i.isSliding||W(k[a].dir=="vert"?"center":"all",!1),xa(a));Ja(a)}var f=r[a],g=n[a],i=l[a],c=!c&&i.isClosed&&g.fxName_open!="none",m=i.isShowing;delete i.isShowing;if(f&&(g.resizable||g.closable)&&(!i.isVisible||i.isSliding))if(i.isHidden&&!m)la(a,!0);else if(k.isLayoutBusy)Ia("open",
a,b);else if(!1!==u(a,g.onopen_start))if(R(a,b),i.minSize>i.maxSize)qa(a,!1),!e&&g.noRoomToOpenTip&&alert(g.noRoomToOpenTip);else{k[a].isMoving=!0;k.isLayoutBusy=!0;b?ha(a,!0):i.isSliding?ha(a,!1):g.slidable&&fa(a,!1);i.noRoom=!1;X(a);i.isVisible=!0;i.isClosed=!1;if(m)i.isHidden=!1;c?(ma(a,!0),f.show(g.fxName_open,g.fxSettings_open,g.fxSpeed_open,function(){ma(a,!1);d()})):(f.show(),d())}},xa=function(a,b){var c=r[a],e=y[a],d=D[a],j=n[a],g=l[a],i=k[a].side.toLowerCase(),m=j.resizerClass,h=j.togglerClass,
A="-"+a;e.css(i,v["inset"+k[a].side]+Q(a)).removeClass(m+"-closed "+m+A+"-closed").addClass(m+"-open "+m+A+"-open");g.isSliding?e.addClass(m+"-sliding "+m+A+"-sliding"):e.removeClass(m+"-sliding "+m+A+"-sliding");j.resizerDblClickToggle&&e.bind("dblclick",aa);S(0,e);j.resizable&&typeof f.fn.draggable=="function"?e.draggable("enable").css("cursor",j.resizerCursor).attr("title",j.resizerTip):g.isSliding||e.css("cursor","default");d&&(d.removeClass(h+"-closed "+h+A+"-closed").addClass(h+"-open "+h+A+
"-open").attr("title",j.togglerTip_open),S(0,d),d.children(".content-closed").hide(),d.children(".content-open").css("display","block"));qa(a,!g.isSliding);f.extend(g,$(c));l.initialized&&(ga("all"),ba(a,!0));if(!b&&(l.initialized||j.triggerEventsOnLoad)&&c.is(":visible"))u(a,j.onopen_end||j.onopen),g.isShowing&&u(a,j.onshow_end||j.onshow),l.initialized&&(u(a,j.onresize_end||j.onresize),ia(a))},Ua=function(a){var b=typeof a,c=b=="string"?a:f(this).data("layoutEdge");b=="object"&&a.stopImmediatePropagation();
l[c].isClosed?T(c,!0):ha(c,!0)},Aa=function(a){function b(){s.isClosed?ha(pane,!1):k[pane].isMoving||M(pane)}var c=J(a)?null:a;$E=c?f(this):r[a];pane=$E.data("layoutEdge");o=n[pane];s=l[pane];$P=r[pane];if(!s.isClosed&&!s.isResizing)if(o.slideTrigger_close=="click")b();else if(!o.preventQuickSlideClose||!k.isLayoutBusy)if(!o.preventPrematureSlideClose||!c||!f.layout.isMouseOverElem(c,$P))c?E.set(pane+"_closeSlider",b,k[pane].isMoving?1E3:300):b()},ma=function(a,b){var c=r[a];if(b)c.css({zIndex:k.zIndex.pane_animate}),
a=="south"?c.css({top:v.insetTop+v.innerHeight-c.outerHeight()}):a=="east"&&c.css({left:v.insetLeft+v.innerWidth-c.outerWidth()});else{c.css({zIndex:l[a].isSliding?k.zIndex.pane_sliding:k.zIndex.pane_normal});a=="south"?c.css({top:"auto"}):a=="east"&&c.css({left:"auto"});var e=n[a];l.browser.msie&&e.fxOpacityFix&&e.fxName_open!="slide"&&c.css("filter")&&c.css("opacity")==1&&c[0].style.removeAttribute("filter")}},fa=function(a,b){var c=n[a],e=y[a],d=c.slideTrigger_open;if(e&&c.slidable){if(d.match(/mouseover/))d=
c.slideTrigger_open="mouseenter";else if(!d.match(/click|dblclick|mouseenter/))d=c.slideTrigger_open="click";e[b?"bind":"unbind"](d+"."+w,Ua).css("cursor",b?c.sliderCursor:"default").attr("title",b?c.sliderTip:"")}},ha=function(a,b){function c(b){E.clear(a+"_closeSlider");b.stopPropagation()}var e=n[a],d=k.zIndex,f=e.slideTrigger_close,g=b?"bind":"unbind",i=r[a],m=y[a];l[a].isSliding=b;E.clear(a+"_closeSlider");b&&fa(a,!1);i.css("zIndex",b?d.pane_sliding:d.pane_normal);m.css("zIndex",b?d.pane_sliding:
d.resizer_normal);if(!f.match(/click|mouseleave/))f=e.slideTrigger_close="mouseleave";m[g](f,Aa);f=="mouseleave"&&(i[g]("mouseleave."+w,Aa),m[g]("mouseenter."+w,c),i[g]("mouseenter."+w,c));b?f=="click"&&!e.resizable&&(m.css("cursor",b?e.sliderCursor:"default"),m.attr("title",b?e.togglerTip_open:"")):E.clear(a+"_closeSlider")},X=function(a,b,c,e){var b=n[a],d=l[a],f=k[a],g=r[a],i=y[a],m=f.dir=="vert",h=!1;if(a=="center"||m&&d.noVerticalRoom)if((h=d.minHeight<=d.maxHeight&&(m||d.minWidth<=d.maxWidth))&&
d.noRoom){g.show();i&&i.show();d.isVisible=!0;d.noRoom=!1;if(m)d.noVerticalRoom=!1;Ma(a)}else if(!h&&!d.noRoom)g.hide(),i&&i.hide(),d.isVisible=!1,d.noRoom=!0;if(a!="center")if(d.minSize<=d.maxSize){if(d.size>d.maxSize?ca(a,d.maxSize,c,e):d.size<d.minSize?ca(a,d.minSize,c,e):i&&g.is(":visible")&&(c=f.side.toLowerCase(),e=d.size+v["inset"+f.side],Z(i,c)!=e&&i.css(c,e)),d.noRoom)d.wasOpen&&b.closable?b.autoReopen?T(a,!1,!0,!0):d.noRoom=!1:la(a,d.wasOpen,!0,!0)}else if(!d.noRoom)d.noRoom=!0,d.wasOpen=
!d.isClosed&&!d.isSliding,d.isClosed||(b.closable?M(a,!0,!0):wa(a,!0))},za=function(a,b,c){var e=n[a],d=e.resizeWhileDragging&&!k.isLayoutBusy;e.autoResize=!1;ca(a,b,c,d)},ca=function(a,b,c,e){var d=n[a],j=l[a],g=r[a],i=y[a],m=k[a].side.toLowerCase(),h="inset"+k[a].side,A=k.isLayoutBusy&&!d.triggerEventsWhileDragging,p;R(a);p=j.size;b=U(a,b);b=z(b,U(a,d.minSize));b=Math.min(b,j.maxSize);if(b<j.minSize)X(a,!1,c);else if(e||b!=p)!c&&l.initialized&&j.isVisible&&u(a,d.onresize_start),g.css(k[a].sizeType.toLowerCase(),
z(1,k[a].dir=="horz"?L(a,b):K(a,b))),j.size=b,f.extend(j,$(g)),i&&g.is(":visible")&&i.css(m,b+v[h]),ba(a),!c&&!A&&l.initialized&&j.isVisible&&(u(a,d.onresize_end||d.onresize),ia(a)),c||(j.isSliding||W(k[a].dir=="horz"?"all":"center",A,e),ga("all")),a=k.altSide[a],b<p&&l[a].noRoom&&(R(a),X(a,!1,c))},W=function(a,b,c){if(!a||a=="all")a="east,west,center";f.each(a.split(","),function(a,d){if(r[d]){var j=n[d],g=l[d],i=r[d],m=!0,h={},m={top:Q("north",!0),bottom:Q("south",!0),left:Q("west",!0),right:Q("east",
!0),width:0,height:0};m.width=v.innerWidth-m.left-m.right;m.height=v.innerHeight-m.bottom-m.top;m.top+=v.insetTop;m.bottom+=v.insetBottom;m.left+=v.insetLeft;m.right+=v.insetRight;f.extend(g,$(i));if(d=="center"){if(!c&&g.isVisible&&m.width==g.outerWidth&&m.height==g.outerHeight)return!0;f.extend(g,ja(d),{maxWidth:m.width,maxHeight:m.height});h=m;h.width=K(d,m.width);h.height=L(d,m.height);m=h.width>0&&h.height>0;if(!m&&!l.initialized&&j.minWidth>0){var k=j.minWidth-g.outerWidth,p=n.east.minSize||
0,q=n.west.minSize||0,t=l.east.size,w=l.west.size,y=t,x=w;k>0&&l.east.isVisible&&t>p&&(y=z(t-p,t-k),k-=t-y);k>0&&l.west.isVisible&&w>q&&(x=z(w-q,w-k),k-=w-x);if(k==0){t!=p&&ca("east",y,!0);w!=q&&ca("west",x,!0);W("center",b,c);return}}}else{f.extend(g,$(i),ja(d));if(!c&&!g.noVerticalRoom&&m.height==g.outerHeight)return!0;h.top=m.top;h.bottom=m.bottom;h.height=L(d,m.height);g.maxHeight=z(0,h.height);m=g.maxHeight>0;if(!m)g.noVerticalRoom=!0}m?(!b&&l.initialized&&u(d,j.onresize_start),i.css(h),f.extend(g,
$(i)),g.noRoom&&X(d),l.initialized&&ba(d)):!g.noRoom&&g.isVisible&&X(d);if(d=="center")i=l.browser,i=i.isIE6||i.msie&&!i.boxModel,r.north&&(i||l.north.tagName=="IFRAME")&&r.north.css("width",K(r.north,v.innerWidth)),r.south&&(i||l.south.tagName=="IFRAME")&&r.south.css("width",K(r.south,v.innerWidth));!b&&l.initialized&&g.isVisible&&(u(d,j.onresize_end||j.onresize),ia(d))}})},ka=function(){f.extend(l.container,$(C));if(v.outerHeight){if(!1===u(null,n.onresizeall_start))return!1;var a,b,c;f.each(["south",
"north","east","west"],function(a,d){r[d]&&(c=l[d],b=n[d],b.autoResize&&c.size!=b.size?ca(d,b.size,!0,!0):(R(d),X(d,!1,!0,!0)))});W("all",!0,!0);ga("all");b=n;f.each(k.allPanes.split(","),function(c,d){if(a=r[d])l[d].isVisible&&u(d,b[d].onresize_end||b[d].onresize),ia(d)});u(null,b.onresizeall_end||b.onresizeall)}},ia=function(a){var b=r[a],c=V[a];n[a].resizeNestedLayout&&(b.data("layoutContainer")?b.layout().resizeAll():c&&c.data("layoutContainer")&&c.layout().resizeAll())},ba=function(a,b){if(!a||
a=="all")a=k.allPanes;f.each(a.split(","),function(a,e){function d(a){return z(h.css.paddingBottom,parseInt(a.css("marginBottom"),10)||0)}function f(){var a=n[e].contentIgnoreSelector,a=i.nextAll().not(a||":lt(0)"),b=a.filter(":visible"),c=b.filter(":last");p={top:i[0].offsetTop,height:i.outerHeight(),numFooters:a.length,hiddenFooters:a.length-b.length,spaceBelow:0};p.spaceAbove=p.top;p.bottom=p.top+p.height;p.spaceBelow=c.length?c[0].offsetTop+c.outerHeight()-p.bottom+d(c):d(i)}var g=r[e],i=V[e],
m=n[e],h=l[e],p=h.content;if(!g||!i||!g.is(":visible"))return!0;if(!1!==u(null,m.onsizecontent_start)){if(!k.isLayoutBusy||p.top==void 0||b||m.resizeContentWhileDragging)f(),p.hiddenFooters>0&&g.css("overflow")=="hidden"&&(g.css("overflow","visible"),f(),g.css("overflow","hidden"));g=h.innerHeight-(p.spaceAbove-h.css.paddingTop)-(p.spaceBelow-h.css.paddingBottom);if(!i.is(":visible")||p.height!=g)Wa(i,g,!0),p.height=g;l.initialized&&(u(e,m.onsizecontent_end||m.onsizecontent),ia(e))}})},ga=function(a){if(!a||
a=="all")a=k.borderPanes;f.each(a.split(","),function(a,c){var e=n[c],d=l[c],j=r[c],g=y[c],i=D[c],h;if(j&&g){var p=k[c].dir,q=d.isClosed?"_closed":"_open",t=e["spacing"+q],u=e["togglerAlign"+q],q=e["togglerLength"+q],w;if(t==0)g.hide();else{!d.noRoom&&!d.isHidden&&g.show();p=="horz"?(w=j.outerWidth(),d.resizerLength=w,g.css({width:z(1,K(g,w)),height:z(0,L(g,t)),left:Z(j,"left")})):(w=j.outerHeight(),d.resizerLength=w,g.css({height:z(1,L(g,w)),width:z(0,K(g,t)),top:v.insetTop+Q("north",!0)}));S(e,
g);if(i){if(q==0||d.isSliding&&e.hideTogglerOnSlide){i.hide();return}else i.show();if(!(q>0)||q=="100%"||q>w)q=w,u=0;else if(J(u))switch(u){case "top":case "left":u=0;break;case "bottom":case "right":u=w-q;break;default:u=Math.floor((w-q)/2)}else d=parseInt(u,10),u=u>=0?d:w-q+d;if(p=="horz"){var x=K(i,q);i.css({width:z(0,x),height:z(1,L(i,t)),left:u,top:0});i.children(".content").each(function(){h=f(this);h.css("marginLeft",Math.floor((x-h.outerWidth())/2))})}else{var B=L(i,q);i.css({height:z(0,B),
width:z(1,K(i,t)),top:u,left:0});i.children(".content").each(function(){h=f(this);h.css("marginTop",Math.floor((B-h.outerHeight())/2))})}S(0,i)}!l.initialized&&e.initHidden&&(g.hide(),i&&i.hide())}}})},C=f(this).eq(0);if(!C.length)return null;if(C.data("layoutContainer"))return f.extend({},window[C.data("layoutContainer")]);var r={},V={},y={},D={},v=l.container,w=l.id;(function(){$a();var a=n;if(!1===u(null,a.onload))return!1;if(!Ra("center").length)return alert("UI Layout Initialization Error\n\nThe center-pane element does not exist.\n\nThe center-pane is a required element."),
null;a.useStateCookie&&a.cookie.autoLoad&&Ga();l.browser={mozilla:f.browser.mozilla,webkit:f.browser.webkit||f.browser.safari,msie:f.browser.msie,isIE6:f.browser.msie&&f.browser.version==6,boxModel:f.support.boxModel};var b=C,c=v.tagName=b.attr("tagName"),e=c=="BODY",d={};v.selector=b.selector.split(".slice")[0];v.ref=c+"/"+v.selector;b.data("layoutContainer",w).data("layoutName",n.name);b.data("layoutCSS")||(e?(d=f.extend(ua(b,"position,margin,padding,border"),{height:b.css("height"),overflow:b.css("overflow"),
overflowX:b.css("overflowX"),overflowY:b.css("overflowY")}),c=f("html"),c.data("layoutCSS",{height:"auto",overflow:c.css("overflow"),overflowX:c.css("overflowX"),overflowY:c.css("overflowY")})):d=ua(b,"position,margin,padding,border,top,bottom,left,right,width,height,overflow,overflowX,overflowY"),b.data("layoutCSS",d));try{if(e)f("html").css({height:"100%",overflow:"hidden",overflowX:"hidden",overflowY:"hidden"}),f("body").css({position:"relative",height:"100%",overflow:"hidden",overflowX:"hidden",
overflowY:"hidden",margin:0,padding:0,border:"none"});else{var d={overflow:"hidden"},h=b.css("position");b.css("height");if(!b.data("layoutRole")&&(!h||!h.match(/fixed|absolute|relative/)))d.position="relative";b.css(d);b.is(":visible")&&b.innerHeight()<2&&alert("UI Layout Initialization Warning\n\nThe layout-container \"CONTAINER\" has no height.\n\nTherefore the layout is 0-height and hence 'invisible'!".replace(/CONTAINER/,v.ref))}}catch(g){}f.extend(l.container,$(b));ab();ba();if(a.scrollToBookmarkOnLoad)b=
self.location,b.hash&&b.replace(b.hash);a.autoBindCustomButtons&&cb();Za();a.resizeWithWindow&&!C.data("layoutRole")&&f(window).bind("resize."+w,Ya);f(window).bind("unload."+w,Pa);l.initialized=!0})();var Ka={options:n,state:l,container:C,panes:r,contents:V,resizers:y,togglers:D,toggle:aa,hide:wa,show:la,open:T,close:M,slideOpen:Ua,slideClose:Aa,slideToggle:function(a){aa(a,!0)},initContent:Sa,sizeContent:ba,sizePane:za,swapPanes:function(a,b){function c(a){var b=r[a],c=V[a];return!b?!1:{pane:a,P:b?
b[0]:!1,C:c?c[0]:!1,state:f.extend({},l[a]),options:f.extend({},n[a])}}function e(a,b){if(a){var c=a.P,d=a.C,e=a.pane,h=k[b],j=h.side.toLowerCase(),p="inset"+h.side,q=f.extend({},l[b]),t=n[b],u={resizerCursor:t.resizerCursor};f.each("fxName,fxSpeed,fxSettings".split(","),function(a,b){u[b]=t[b];u[b+"_open"]=t[b+"_open"];u[b+"_close"]=t[b+"_close"]});r[b]=f(c).data("layoutEdge",b).css(k.hidden).css(h.cssReq);V[b]=d?f(d):!1;n[b]=f.extend({},a.options,u);l[b]=f.extend({},a.state);c.className=c.className.replace(RegExp(t.paneClass+
"-"+e,"g"),t.paneClass+"-"+b);Ta(b);h.dir!=k[e].dir?(c=g[b]||0,R(b),c=z(c,l[b].minSize),za(b,c,!0)):y[b].css(j,v[p]+(l[b].isVisible?Q(b):0));a.state.isVisible&&!q.isVisible?xa(b,!0):(ya(b),fa(b,!0));a=null}}l[a].edge=b;l[b].edge=a;var d=!1;!1===u(a,n[a].onswap_start)&&(d=!0);!d&&!1===u(b,n[b].onswap_start)&&(d=!0);if(d)l[a].edge=a,l[b].edge=b;else{var d=c(a),h=c(b),g={};g[a]=d?d.state.size:0;g[b]=h?h.state.size:0;r[a]=!1;r[b]=!1;l[a]={};l[b]={};D[a]&&D[a].remove();D[b]&&D[b].remove();y[a]&&y[a].remove();
y[b]&&y[b].remove();y[a]=y[b]=D[a]=D[b]=!1;e(d,b);e(h,a);d=h=g=null;r[a]&&r[a].css(k.visible);r[b]&&r[b].css(k.visible);ka();u(a,n[a].onswap_end||n[a].onswap);u(b,n[b].onswap_end||n[b].onswap)}},resizeAll:ka,destroy:function(){f(window).unbind("."+w);f(document).unbind("."+w);window[w]=null;var a=v.tagName=="BODY",b,c,e,d;f.each(k.allPanes.split(","),function(a,g){b=r[g];if(!b)return!0;g!="center"&&(D[g]&&D[g].remove(),y[g].remove());c=n[g].paneClass;e=c+"-"+g;d=[c,c+"-open",c+"-closed",c+"-sliding",
e,e+"-open",e+"-closed",e+"-sliding"];f.merge(d,va(b,!0));b.removeClass(d.join(" ")).removeData("layoutRole").removeData("layoutEdge").unbind("."+w).unbind("mouseenter").unbind("mouseleave");b.data("layoutContainer")||b.css(b.data("layoutCSS"))});C.removeData("layoutContainer");C.data("layoutEdge")||C.css(C.data("layoutCSS"));a&&f("html").css(f("html").data("layoutCSS"));Pa();(a=n.name)&&window[a]&&(window[a]=null)},setSizeLimits:R,bindButton:Y,addToggleBtn:na,addOpenBtn:oa,addCloseBtn:Ba,addPinBtn:Ca,
allowOverflow:F,resetOverflow:N,encodeJSON:Fa,decodeJSON:Ea,getState:sa,getCookie:Da,saveCookie:ra,deleteCookie:function(){ra("",{expires:-1})},loadCookie:Ga,loadState:Ha,cssWidth:K,cssHeight:L};return window[w]=Ka}})(jQuery);

